### ISSUE TITLE
404 on refreshing page on any screen

### ISSUE THREAD

**Issue by init-five** [init-five/Smart-Cut-Portal#5]
**Video**

https://github.com/init-five/Smart-Cut-Portal/assets/78718349/f0c2a43e-0505-4e6d-a2c2-a2803e185081

**Comment by Wali-Ullah-Asim** [comment]
Done

**Comment by init-five** [comment]
@Wali-Ullah-Asim still getting this error on refreshing


![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/c3dc4561-4156-46cb-9678-7b2e18528d32)

**API**


![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/a963b031-1331-460d-821a-7744c32d1f71)

**Comment by init-five** [comment]
page refresh


![Image](https://github.com/init-five/Smart-Cut-Portal/assets/78718349/1ef0453c-2462-4c73-9b75-ac263796cf97)
